# Generated by Django 4.0.3 on 2022-04-14 14:29

import django.contrib.postgres.fields.citext
from django.contrib.postgres.operations import CITextExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0001_initial"),
    ]

    operations = [
        CITextExtension(),
        migrations.AlterField(
            model_name="exercise",
            name="name",
            field=django.contrib.postgres.fields.citext.CICharField(
                max_length=150, unique=True
            ),
        ),
    ]
