# Generated by Django 4.0.3 on 2022-04-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0002_alter_exercise_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workout",
            name="name",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterUniqueTogether(
            name="workout",
            unique_together={("name", "date")},
        ),
    ]
