# Generated by Django 4.0.4 on 2022-04-15 15:13

import django.contrib.postgres.fields.citext
from django.contrib.postgres.operations import CITextExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0003_alter_workout_name_alter_workout_unique_together"),
    ]

    operations = [
        CITextExtension(),
        migrations.AlterField(
            model_name="workout",
            name="name",
            field=django.contrib.postgres.fields.citext.CICharField(max_length=150),
        ),
    ]
