# Generated by Django 4.0.4 on 2022-04-20 06:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0004_alter_workout_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="set",
            name="weight",
            field=models.PositiveSmallIntegerField(
                default=0,
                validators=[
                    django.core.validators.MaxValueValidator(
                        2000,
                        message="Who are you super man? Weight must be less than or equal to 2000.",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="workout",
            name="date",
            field=models.DateField(verbose_name="workout date"),
        ),
    ]
