# Generated by Django 4.0.4 on 2022-05-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0006_workout_is_deleted_alter_set_weight"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workout",
            name="is_deleted",
        ),
        migrations.AddField(
            model_name="workout",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="workout",
            index=models.Index(fields=["user"], name="workouts_wo_user_id_cea72a_idx"),
        ),
    ]
