# Generated by Django 4.0.4 on 2022-05-27 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0007_remove_workout_is_deleted_workout_deleted_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="set",
            old_name="_name",
            new_name="name",
        ),
    ]
